# ADN T002 ~ Molecular Descriptors and Fingerprints

Authors:

* Adnane Aouidate, 2022, Structural Bioinformatics and Chemoinformatics, Institute of Organic and Analytical Chemistry (ICOA), Orl√©ans, France.
* Update , 2023, Ait Melloul Faculty of Applied Sciences, Ibn Zohr University, Agadir, Morocco.

## Aim of this Notebook

In the current tutorial we will learn how to use python combined with Rdkit in order to calculate different molecular descriptors descriptors, using in built *rdkit* functions and also third party software like *Mordred*.

As a definition : a **Molecular Descriptor(MD)** is the final result of a logical and mathematical procedure that transforms chemical information of a molecule, such as structural features, into useful numbers or the result of standardized experiments.

Utility :

They can be used :
* To compare molecules and/or their properties (Molecular similarity), so they can help us to identify new molecules with desired properties and biological activity.
* To develop QSAR models 
* To cluster compounds based on their physicochemical attributes
* To study the chemical space 
* To check drug likness of compounds

## Molecular descriptors

*Similarity can be assessed in many different ways depending on the application (see J. Med. Chem. (2014), 57, 3186-3204</a>):*

* 1D molecular descriptor: Solubility, logP, molecular weight, melting point.
    * Global descriptor: only one value represents the whole molecule
    * Usually do not contain enough information to be applied to machine learning (ML)
    * Can be added to 2D fingerprints to improve molecular encoding for ML
* 2D molecular descriptors: Molecular graphs, paths, fragments, atom environments
    * Detailed representation of individual parts of the molecule
    * Contains many features/bits per molecule called fingerprints
    * Very often used in similarity search and ML
* 3D molecular descriptors: Shape, stereochemistry, Polar Surface area (PSA), CoMFA
    * Less robust than 2D representations because of molecule flexibility (what is the "right" conformation of a molecule?) Biological similarity
    * Biological fingerprint, e.g. individual bits represent bioactivity measure against different targets
    * Independent of molecular structure
    * Requires experimental (or predicted) data
    
## Tools for descriptors calculation

* [Rdkit](https://www.rdkit.org/docs/source/rdkit.Chem.Descriptors.html), [Mordred](https://github.com/mordred-descriptor/mordred), [Chamxon](https://chemaxon.com/), [CDK](http://www.rguha.net/code/java/cdkdesc.html), [E-Dragon](https://vcclab.org/lab/edragon/), [alvaDesc](https://www.alvascience.com/alvadesc/), [MOLD2](https://www.fda.gov/science-research/bioinformatics-tools/mold2)...

**Requirments**

Rdki : https://www.rdkit.org/

Installation via Anaconda : conda install -c rdkit rdkit

Mordred : https://github.com/mordred-descriptor/mordred

Installation via Anaconda : conda install -c conda-forge mordred

In [3]:
import pandas as pd
import numpy as np
from rdkit import Chem,DataStructs
from rdkit.Chem import AllChem, Descriptors, MACCSkeys
from rdkit.Chem.Draw import IPythonConsole
from mordred import Calculator, descriptors

Let's first read the sdf file

In [6]:
file = './databases/data-test.sdf'
mols = []
for m in Chem.SDMolSupplier(file):
    if m is not None:
        mols.append(m)

In [7]:
len(mols)

50

### Molecular descriptors using *Rdkit*

In [8]:
desc = []

for m in mols :
    desc.append([Descriptors.MolLogP(m),
    Descriptors.HeavyAtomCount(m),
    Descriptors.MolMR(m),
    Descriptors.MolWt(m),
    Descriptors.NumHAcceptors(m),
    Descriptors.NumHDonors(m)])
columns = ['logp', 'HAC', 'MMR', 'MW', 'NHA', 'NHB']
desc = pd.DataFrame(desc, columns= columns)

In [9]:
desc

       logp  HAC       MMR        MW  NHA  NHB
0   2.14360   12   47.4680   156.188    2    0
1   0.39950   10   35.3720   138.174    4    0
2  -0.26630    6   25.5104    86.158    0    1
3  -0.48910   17   68.2684   236.403    0    2
4   2.78300   14   57.0440   180.210    2    0
5   2.16120   25   95.9625   344.519    2    2
6   2.16120   25   95.9625   344.519    2    2
7  -2.93810   56  186.3958   804.880   18   11
8  -5.11390   67  219.0292   967.021   23   14
9  -2.93810   56  186.3958   804.880   18   11
10 -2.93810   56  186.3958   804.880   18   11
11 -2.93810   56  186.3958   804.880   18   11
12 -5.11390   67  219.0292   967.021   23   14
13 -5.11390   67  219.0292   967.021   23   14
14 -2.93810   56  186.3958   804.880   18   11
15 -2.93810   56  186.3958   804.880   18   11
16 -2.93810   56  186.3958   804.880   18   11
17 -2.93810   56  186.3958   804.880   18   11
18 -2.93810   56  186.3958   804.880   18   11
19 -2.93810   56  186.3958   804.880   18   11
20 -2.93810   56  186.3958   804.880   18   11
21 -2.93810   56  186.3958   804.880   18   11
22 -5.11390   67  219.0292   967.021   23   14
23 -5.11390   67  219.0292   967.021   23   14
24 -0.76230   45  153.7624   642.739   13    8
25 -4.08470   66  217.6394   951.022   22   13
26 -4.47480   65  213.0224   936.995   22   13
27 -4.47480   65  213.0224   936.995   22   13
28 -4.47480   65  213.0224   936.995   22   13
29 -5.11390   67  219.0292   967.021   23   14
30 -5.11390   67  219.0292   967.021   23   14
31 -7.28970   78  251.6626  1129.162   28   17
32 -5.11390   67  219.0292   967.021   23   14
33 -2.93810   56  186.3958   804.880   18   11
34  1.82360   20   70.6766   280.320    5    2
35  1.78160   26   95.1424   362.466    5    3
36  1.55760   26   95.0484   360.450    5    3
37  3.21270   29  108.3024   402.531    5    3
38  1.76580   26   94.0486   358.434    5    2
39  2.53270   26   88.5558   358.390    6    1
40  1.20459   19   67.7948   261.297    4    1
41  1.97540   26  107.3334   358.614    0    2
42  2.41960   18   66.7220   246.306    3    0
43  2.45180   18   65.8530   248.322    3    0
44  1.39040   19   68.1118   262.305    4    1
45  1.59310   18   70.4577   248.390    1    1
46  0.92540   15   53.1042   231.293    4    0
47  1.51230   13   45.7110   182.219    3    0
48 -2.09446   27   94.5902   375.361    9    4
49  2.40170   11   44.2360   152.237    1    0

### Molecular descriptors using *Mordred*

In [4]:
df = pd.read_csv("./databases/acetylcholinesterase_Ki_pKi_bioactivity_data_curated.csv", index_col="molecule_chembl_id")

Let's first read the database that we got from the the jupyter notebook ADN_T000 in this series of notebooks

In [5]:
df.head()

,units,Ki,smiles,pKi
molecule_chembl_id,,,,
CHEMBL11805,nM,0.104,COc1ccccc1CN(C)CCCCCC(=O)N(C)CCCCCCCCN(C)C(=O)...,9.982967
CHEMBL208599,nM,0.026,CCC1=CC2Cc3nc4cc(Cl)ccc4c(N)c3[C@@H](C1)C2,10.585027
CHEMBL60745,nM,1.630,CC[N+](C)(C)c1cccc(O)c1.[Br-],8.787812
CHEMBL95,nM,151.000,Nc1c2c(nc3ccccc13)CCCC2,6.821023
CHEMBL173309,nM,12.200,CCN(CCCCCC(=O)N(C)CCCCCCCCN(C)C(=O)CCCCCN(CC)C...,7.913640

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 472 entries, CHEMBL11805 to CHEMBL193996
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   units   472 non-null    object
 1   Ki      472 non-null    float64
 2   smiles  472 non-null    object
 3   pKi     472 non-null    float64
dtypes: float64(2), object(2)
memory usage: 18.4+ KB

Here, we will get all molecules as mols rdkit objects

In [51]:
mols = [Chem.MolFromSmiles(smi) for smi in df.smiles]

### Create descriptor calculato

In [52]:
Calc = Calculator(descriptors, ignore_3D= True)

In [53]:
len(Calc.descriptors)

1613

# Calculate descriptors and store them to a dataframe

In [54]:
df1 = Calc.pandas(mols)

  0%|                                           | 1/472 [00:01<15:30,  1.98s/it]

/Users/adnane/opt/anaconda3/envs/ADN/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  2%|‚ñâ                                         | 10/472 [00:03<01:32,  5.01it/s]

/Users/adnane/opt/anaconda3/envs/ADN/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  3%|‚ñà‚ñè                                        | 13/472 [00:06<03:29,  2.19it/s]

/Users/adnane/opt/anaconda3/envs/ADN/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  8%|‚ñà‚ñà‚ñà‚ñå                                      | 40/472 [00:09<01:11,  6.04it/s]

/Users/adnane/opt/anaconda3/envs/ADN/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

  9%|‚ñà‚ñà‚ñà‚ñã                                      | 42/472 [00:09<01:08,  6.23it/s]

/Users/adnane/opt/anaconda3/envs/ADN/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 53%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñâ                   | 252/472 [01:23<02:30,  1.46it/s]

/Users/adnane/opt/anaconda3/envs/ADN/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 54%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñâ                   | 253/472 [01:24<02:23,  1.53it/s]

/Users/adnane/opt/anaconda3/envs/ADN/lib/python3.7/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 472/472 [18:44<00:00,  2.38s/it]

In [55]:
df1.head()

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,35.142811,24.264889,0,2,60.122409,2.279705,4.55941,60.122409,1.25255,4.737539,...,10.238852,84.598254,666.508407,5.846565,14630,63,218.0,238.0,16.611111,11.361111
1,16.987142,12.790496,0,0,27.467293,2.533089,5.066178,27.467293,1.307966,4.015374,...,10.293467,55.839709,298.123676,7.453092,842,39,120.0,147.0,6.25,4.472222
2,8.850899,8.508709,1,1,multiple fragments (SpAbs_A/SpAbs),multiple fragments (SpMax_A/SpMax),multiple fragments (SpDiam_A/SpDiam),multiple fragments (SpAD_A/SpAD),multiple fragments (SpMAD_A/SpMAD),multiple fragments (LogEE_A/LogEE),...,9.303375,43.773162,245.041526,8.449708,1200000190,16,58.0,65.0,divide by zero encountered in power (mZagreb1),2.708333
3,11.968445,9.625522,0,0,20.264831,2.459954,4.919908,20.264831,1.350989,3.67295,...,9.827416,47.796305,198.115698,6.831576,326,25,82.0,99.0,3.805556,3.277778
4,36.338245,25.499176,0,2,63.382841,2.287195,4.57439,63.382841,1.267657,4.776866,...,10.283053,86.794615,694.539707,5.787831,16085,67,226.0,248.0,17.111111,12.027778

### Let's set the index cas cid of the molecules

In [56]:
df1.set_index(df.index, inplace=True)

In [59]:
df1["pKi"] = df["pKi"]

In [60]:
df1.head()

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2,pKi
molecule_chembl_id,,,,,,,,,,,,,,,,,,,,,
CHEMBL11805,35.142811,24.264889,0,2,60.122409,2.279705,4.55941,60.122409,1.25255,4.737539,...,84.598254,666.508407,5.846565,14630,63,218.0,238.0,16.611111,11.361111,9.982967
CHEMBL208599,16.987142,12.790496,0,0,27.467293,2.533089,5.066178,27.467293,1.307966,4.015374,...,55.839709,298.123676,7.453092,842,39,120.0,147.0,6.25,4.472222,10.585027
CHEMBL60745,8.850899,8.508709,1,1,multiple fragments (SpAbs_A/SpAbs),multiple fragments (SpMax_A/SpMax),multiple fragments (SpDiam_A/SpDiam),multiple fragments (SpAD_A/SpAD),multiple fragments (SpMAD_A/SpMAD),multiple fragments (LogEE_A/LogEE),...,43.773162,245.041526,8.449708,1200000190,16,58.0,65.0,divide by zero encountered in power (mZagreb1),2.708333,8.787812
CHEMBL95,11.968445,9.625522,0,0,20.264831,2.459954,4.919908,20.264831,1.350989,3.67295,...,47.796305,198.115698,6.831576,326,25,82.0,99.0,3.805556,3.277778,6.821023
CHEMBL173309,36.338245,25.499176,0,2,63.382841,2.287195,4.57439,63.382841,1.267657,4.776866,...,86.794615,694.539707,5.787831,16085,67,226.0,248.0,17.111111,12.027778,7.913640

### Check for none values

In [81]:
df1.isnull().sum().sum()

0

In [89]:
data_columns = df1.columns 
data_indices = df1.index

In [90]:
df2 = (df1.drop(columns= data_columns, axis=1).join(df1[data_columns]).apply(pd.to_numeric, errors='coerce'))

In [91]:
df2.head()

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2,pKi
molecule_chembl_id,,,,,,,,,,,,,,,,,,,,,
CHEMBL11805,35.142811,24.264889,0,2,60.122409,2.279705,4.559410,60.122409,1.252550,4.737539,...,84.598254,666.508407,5.846565,14630,63,218.0,238.0,16.611111,11.361111,9.982967
CHEMBL208599,16.987142,12.790496,0,0,27.467293,2.533089,5.066178,27.467293,1.307966,4.015374,...,55.839709,298.123676,7.453092,842,39,120.0,147.0,6.250000,4.472222,10.585027
CHEMBL60745,8.850899,8.508709,1,1,NaN,NaN,NaN,NaN,NaN,NaN,...,43.773162,245.041526,8.449708,1200000190,16,58.0,65.0,NaN,2.708333,8.787812
CHEMBL95,11.968445,9.625522,0,0,20.264831,2.459954,4.919908,20.264831,1.350989,3.672950,...,47.796305,198.115698,6.831576,326,25,82.0,99.0,3.805556,3.277778,6.821023
CHEMBL173309,36.338245,25.499176,0,2,63.382841,2.287195,4.574390,63.382841,1.267657,4.776866,...,86.794615,694.539707,5.787831,16085,67,226.0,248.0,17.111111,12.027778,7.913640

In [92]:
df2.isnull().sum().sum()

98525

In [93]:
df2.dropna(how="any", inplace=True, axis = 1)

In [94]:
df2.isnull().sum().sum()

0

In [95]:
df2.head()

,ABC,ABCGG,nAcid,nBase,nAromAtom,nAromBond,nAtom,nHeavyAtom,nSpiro,nBridgehead,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb2,pKi
molecule_chembl_id,,,,,,,,,,,,,,,,,,,,,
CHEMBL11805,35.142811,24.264889,0,2,12,12,114,48,0,0,...,10.238852,84.598254,666.508407,5.846565,14630,63,218.0,238.0,11.361111,9.982967
CHEMBL208599,16.987142,12.790496,0,0,10,11,40,21,0,2,...,10.293467,55.839709,298.123676,7.453092,842,39,120.0,147.0,4.472222,10.585027
CHEMBL60745,8.850899,8.508709,1,1,6,6,29,13,0,0,...,9.303375,43.773162,245.041526,8.449708,1200000190,16,58.0,65.0,2.708333,8.787812
CHEMBL95,11.968445,9.625522,0,0,10,11,29,15,0,0,...,9.827416,47.796305,198.115698,6.831576,326,25,82.0,99.0,3.277778,6.821023
CHEMBL173309,36.338245,25.499176,0,2,12,12,120,50,0,0,...,10.283053,86.794615,694.539707,5.787831,16085,67,226.0,248.0,12.027778,7.913640

Save the resulted dataset

In [103]:
df2.to_csv("./databases/acetylcholinesterase_pKi_mordredMD.csv", index=True)

Check the dataset

In [104]:
df3 = pd.read_csv("./databases/acetylcholinesterase_pKi_mordredMD.csv", index_col=0)

In [105]:
df3.head()

,ABC,ABCGG,nAcid,nBase,nAromAtom,nAromBond,nAtom,nHeavyAtom,nSpiro,nBridgehead,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb2,pKi
molecule_chembl_id,,,,,,,,,,,,,,,,,,,,,
CHEMBL11805,35.142811,24.264889,0,2,12,12,114,48,0,0,...,10.238852,84.598254,666.508407,5.846565,14630,63,218.0,238.0,11.361111,9.982967
CHEMBL208599,16.987142,12.790496,0,0,10,11,40,21,0,2,...,10.293467,55.839709,298.123676,7.453092,842,39,120.0,147.0,4.472222,10.585027
CHEMBL60745,8.850899,8.508709,1,1,6,6,29,13,0,0,...,9.303375,43.773162,245.041526,8.449708,1200000190,16,58.0,65.0,2.708333,8.787812
CHEMBL95,11.968445,9.625522,0,0,10,11,29,15,0,0,...,9.827416,47.796305,198.115698,6.831576,326,25,82.0,99.0,3.277778,6.821023
CHEMBL173309,36.338245,25.499176,0,2,12,12,120,50,0,0,...,10.283053,86.794615,694.539707,5.787831,16085,67,226.0,248.0,12.027778,7.913640

### Molecular fingerprints
Will be calculated soon !!

In [6]:
df.smiles

molecule_chembl_id
CHEMBL11805      COc1ccccc1CN(C)CCCCCC(=O)N(C)CCCCCCCCN(C)C(=O)...
CHEMBL208599            CCC1=CC2Cc3nc4cc(Cl)ccc4c(N)c3[C@@H](C1)C2
CHEMBL60745                          CC[N+](C)(C)c1cccc(O)c1.[Br-]
CHEMBL95                                   Nc1c2c(nc3ccccc13)CCCC2
CHEMBL173309     CCN(CCCCCC(=O)N(C)CCCCCCCCN(C)C(=O)CCCCCN(CC)C...
                                       ...
CHEMBL5220695        CC(C)(C)OC(=O)Nc1ccc(O)c(C(=O)NCCCN2CCCCC2)c1
CHEMBL5219239         CC1CCCCN1CCCNC(=O)c1cc(NC(=O)OC(C)(C)C)ccc1O
CHEMBL5218804                   COc1cccc2c1CCC(NC(=O)OCc1ccccc1)C2
CHEMBL5219425                 CCN(CC)C(=O)OC1C[N+]2(C)CCC1CC2.[I-]
CHEMBL193996                           O=C(Nc1ccccc1)OC1CN2CCC1CC2
Name: smiles, Length: 472, dtype: object

In [22]:
table = pd.DataFrame()
for i, mol in df.smiles) :
    mol = Chem.MolFromSmiles(mol)
    if mol is not None:
        #print(mol)
        table.loc[i,'Mol']=mol
        table.loc[i,"MCCS"]=MACCSkeys.GenMACCSKeys(mol)

In [23]:
table

,Mol,MCCS
0,<rdkit.Chem.rdchem.Mol object at 0x7f9898c6d440>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,<rdkit.Chem.rdchem.Mol object at 0x7f9898d85940>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,<rdkit.Chem.rdchem.Mol object at 0x7f9898904170>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,<rdkit.Chem.rdchem.Mol object at 0x7f9898918e40>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,<rdkit.Chem.rdchem.Mol object at 0x7f98987c1760>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...
467,<rdkit.Chem.rdchem.Mol object at 0x7f9898dbc9e0>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
468,<rdkit.Chem.rdchem.Mol object at 0x7f9898dbcb70>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
469,<rdkit.Chem.rdchem.Mol object at 0x7f9898dbcc60>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
470,<rdkit.Chem.rdchem.Mol object at 0x7f9898dbc260>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
471,<rdkit.Chem.rdchem.Mol object at 0x7f9898dbe5d0>,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [27]:
def get_fingerprints(mol,method = 'morgan2'):  
    #for mol in df[smiles]:
    mol = Chem.MolFromSmiles(mol)
    if mol is not None:
        if method == 'MCCS':
             return MACCSkeys.GenMACCSKeys(mol)
        if method == 'morgan2':
            return AllChem.GetHashedAtomPairFingerprintAsBitVect(mol, nBits=2048)

In [30]:
df["morgan2"] = df["smiles"].apply(get_fingerprints)

In [31]:
df

,units,Ki,smiles,pKi,MCCS,morgan2
molecule_chembl_id,,,,,,
CHEMBL11805,nM,0.104,COc1ccccc1CN(C)CCCCCC(=O)N(C)CCCCCCCCN(C)C(=O)...,9.982967,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
CHEMBL208599,nM,0.026,CCC1=CC2Cc3nc4cc(Cl)ccc4c(N)c3[C@@H](C1)C2,10.585027,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
CHEMBL60745,nM,1.630,CC[N+](C)(C)c1cccc(O)c1.[Br-],8.787812,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
CHEMBL95,nM,151.000,Nc1c2c(nc3ccccc13)CCCC2,6.821023,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
CHEMBL173309,nM,12.200,CCN(CCCCCC(=O)N(C)CCCCCCCCN(C)C(=O)CCCCCN(CC)C...,7.913640,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...,...
CHEMBL5220695,nM,120.000,CC(C)(C)OC(=O)Nc1ccc(O)c(C(=O)NCCCN2CCCCC2)c1,6.920819,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
CHEMBL5219239,nM,170.000,CC1CCCCN1CCCNC(=O)c1cc(NC(=O)OC(C)(C)C)ccc1O,6.769551,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
CHEMBL5218804,nM,0.264,COc1cccc2c1CCC(NC(=O)OCc1ccccc1)C2,9.578396,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
CHEMBL5219425,nM,3500.000,CCN(CC)C(=O)OC1C[N+]2(C)CCC1CC2.[I-],5.455932,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
CHEMBL193996,nM,1000.000,O=C(Nc1ccccc1)OC1CN2CCC1CC2,6.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."